apiVersion: apps/v1
kind: Deployment
metadata:
  name: piazza-deployment
  labels:
    app: piazza
spec:
  replicas: 5
  selector:
    matchLabels:
      app: piazza
  template:
    metadata:
      labels:
        app: piazza
    spec:
      containers:
        - name: piazza
          image: floraugo/piazza-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: piazza-config
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: piazza-secrets
                  key: MONGO_URI
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: piazza-secrets
                  key: JWT_SECRET
            - name: PORT
              value: "5000"
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 5
      imagePullSecrets:
        - name: dockerhub-secret

