apiVersion: v1
kind: Service
metadata:
  name: piazza-service
  labels:
    app: piazza
spec:
  type: LoadBalancer
  selector:
    app: piazza
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
